// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Suz.Projetos.Domain.Entities;
using Suz.Projetos.Persistence;

#nullable disable

namespace Suz.Projetos.Persistence.Migrations
{
    [DbContext(typeof(ProjetosContext))]
    partial class ProjetosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Suz.Projetos.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Suz.Projetos.Domain.Entities.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoProjeto")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloProjeto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Suz.Projetos.Domain.Entities.Categoria", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataCriacao")
                    .HasColumnType("TEXT");

                b.Property<string>("DescricaoCategoria")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<Categoria>("idCategoria")
                    .IsRequired() 
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Categoria");
            });

            modelBuilder.Entity("Suz.Projetos.Domain.Entities.SubCategoria", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("DataCriacao")
                    .HasColumnType("TEXT");

                b.Property<string>("DescricaoSubCategoria")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");
 

                b.HasKey("Id");

                b.ToTable("            modelBuilder.Entity(\"Suz.Projetos.Domain.Entities.SubCategoria\", b =>\r\n");
            });
#pragma warning restore 612, 618
        }
    }
}
